name: Test Suite

on:
  push:
    branches: [main, dev] # Add dev branch here
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Debug package.json
        run: |
          echo "Git status:"
          git status
          echo "\nPackage.json contents:"
          cat package.json
          echo "\nGit log (last 3 commits):"
          git log -3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Enable Corepack
        run: corepack enable

      - name: Setup pnpm
        run: corepack prepare pnpm@9.1.4 --activate

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
